### ISSUE TITLE
Ajour removes Addons on its own when Addon removed from Curse(?)

### ISSUE THREAD

**Issue by Bl4ckthunder** [ajour/ajour#628]
Hi,
to bad i realized to late, so i cant give an Log when it probaly happened.
But when i logged in today a Addon just vanished. After Checking it got removed from Curseforge.
Im 101% sure i didnt delete it myself. 
So it could only done by Ajour.
Trying to find a backup of that addon and try to see what happens, but yet not successfull.
So i open this ticket so you can have a look at it?

Thx

**Comment by casperstorm** [comment]
This morning there was an issue with Curse API. It should be resolved by now, however.
Ajour removes addons if you either press delete or if you have a addon which eg. consists of 3 folders: `[foo-a], [foo-b], [foo-c]` and then an update groups them together into `[foo-abc]` then it will remove the old once during the update.

So, unless either of those two things happen then it was not Ajour. 🙂

**Comment by Bl4ckthunder** [comment]
Well, last week the Addon was still working. Since then i just updated All addons with ajour, today i login, and it was gone.
It was https://www.curseforge.com/wow/addons/minimap-button-frame-fan-update , which is now gone why ever.
The Addon calls 3 Folders, Its Main Folder and 2 Skin Folders, the 2 Skin Folders still existed. But i guess thats not a case with [foo-abc]
The original Addon doesnt get updated since years, but i find another Fixed Version outside of Curse. 
Gona backup addon folders for now, but put that addon on Exclude list in Ajour just to be sure.
As said im SURE i didnt delete it on my own, i always do only "update all". 
But if you are sure Ajour wont do it also, i just have no idea what happened. 
You can close it, and i Monitor my Addon Folder now better :)

**Comment by casperstorm** [comment]
Reopen, or ping me if something similar happens again, @Bl4ckthunder.
